spring:
  profiles:
    activate:
  datasource:
    url: jdbc:h2:tcp://localhost/~/schedule
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql:
          use_sql_comments: true

  jwt:
    secretkey: "secret-key-456456"
    token:
      access:
        expire: 3600000
      refresh:
        expire: 1209600000

logging.level:
  org.hibernate.SQL: debug