spring:
  data:
    web:
      pageable:
        default-page-size: 10
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/schedule?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 456456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jwt:
    secretkey: "secret-key-456456"
    token:
      access:
        expire: 36000000
      refresh:
        expire: 1209600000
  mail:
    host: smtp.gmail.com
    port: 587
    username: alsgus235
    password: tcaomxxolgxvhccr

    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug