spring:
  data:
    web:
      pageable:
        default-page-size: 10
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://schedule.crsiw0a4g3yl.ap-northeast-2.rds.amazonaws.com:3306/schedule
    username: admin
    password: "!dongseo1617!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  jwt:
    secretkey: "secret-key-456456"
    token:
      access:
        expire: 36000000
      refresh:
        expire: 1209600000
  mail:
    host: smtp.gmail.com
    port: 587
    username: alsgus235
    password: tcaomxxolgxvhccr

    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging.level:
  org.hibernate.SQL: debug