spring:
#  data:
#    web:
#      pageable:
#        default-page-size: 100
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/schedule
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug